### ISSUE TITLE
cmake failed with Python bindings for sddc_source.h are out of sync

### ISSUE THREAD

**Issue by sueng66** [ourstarsjp/gr-sddc#1]
I resolve this error by manual editing python/bindings/sddc_source_python.cc and change BINDTOOL_HEADER_FILE_HASH to BINDTOOL_HEADER_FILE_HASH(1122bee43a5828e8cf21575c2d6860fc) after manual hash using md5sum sddc_source.h

**Comment by noritsuna** [comment]
Thank you for your report!
